### ISSUE TITLE
Script not working (Run Once Mode), no reason identifiable

### ISSUE THREAD

**Issue by Gi7w0rm** [hpthreatresearch/subcrawl#2]
Hello there, 
just tried using the Tool in run once mode on a fresh install of Ubuntu
```
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
```

Did the commands mentioned in the readme:
```
$ sudo apt install build-essential
$ pip3 install -r requirements.txt
```
everything fine. Created a file in a seperate folder containing the urls to scan:
<img width="205" alt="Urls" src="https://user-images.githubusercontent.com/89871181/157757091-2d2239a1-c899-45c8-a8f4-05036c3478ce.PNG">

manually confirmed them beeing up:
<img width="261" alt="eg_odir" src="https://user-images.githubusercontent.com/89871181/157757382-f5b922c5-88ea-4c22-96f2-3d5b3fce2fef.PNG">
(Carefull, malware!)

And then run your tool using the commands:
``` 
python3 subcrawl.py -f '/home/ubuntu/Desktop/OpenDirs/Ahmad_The_Mastermind.txt' -p YARAProcessing,PayloadProcessing,JARMProcessing,ClamAVProcessing -s SqliteStorage
```    
```
python3 subcrawl.py -f '/home/ubuntu/Desktop/OpenDirs/Ahmad_The_Mastermind.txt' -p YARAProcessing,PayloadProcessing,JARMProcessing,ClamAVProcessing -s ConsoleStorage
```  
and   
```
python3 subcrawl.py -f '/home/ubuntu/Desktop/OpenDirs/Ahmad_The_Mastermind.txt' -p YARAProcessing,PayloadProcessing -s SqliteStorage
```  

With all commands I got following output:
<img width="962" alt="eg_usage" src="https://user-images.githubusercontent.com/89871181/157757911-e1ad14b0-c010-4fd8-831a-c13cd42409f9.PNG">

As you can see the tool clearly identifies the Hosts, but then does not proceed to scan anything. There is also no apparend Error message, neither on the screen nor in the crawler.log file...
What am I missing here ?
Please help

Best regards
Gi7w0rm

**Comment by jstrosch** [comment]
Hi @Gi7w0rm - while it's possible that there was no output to report, it's likely a bigger issue is at play. I've just pushed an update that fixes a bug in the ConsoleStorage module when handling JARMProcessing output. If you could edit your config.yml to change the *log_level* to DEBUG, then you'll get more output to the console and the the log file.  Then, if you could pull the latest changes and run the command:

`python3 -f <your_file> -p PayloadProcessing -s ConsoleStorage`

Let's see what happens. Once we can confirm working output, we can add in additional modules and troubleshoot if necessary.

Thanks,
Josh

**Comment by Gi7w0rm** [comment]
Hey @jstrosch , I just took the time to do as you suggested. 
Oddly enough, I got a pretty weird behaviour that I can't really understand. After deleting the initial "subcrawler" folder, by which I mean the full git pull, and doing a totally new pull, setting the log level to "DEBUG" results in following output:  
<img width="650" alt="already_scanned" src="https://user-images.githubusercontent.com/89871181/158296063-b21bf850-1162-492e-85e8-9a7b773618d8.PNG">
This appears pretty weird to me as I don't know how a tool that has never been run is able to determine that a Domain has already been scanned ? I even fully deleted the Trash folder before running the fresh install,.Also, the DB file in 
Or is it just that the Domain appears several times in the input ?
Input file has not changed at all, so same as in the issue opening message.

Feel free to ask whatever you need for further debugging, I will gladly provide further info. 

Thanks for taking your time
Gi7w0rm

**Comment by jstrosch** [comment]
Hi @Gi7w0rm - that message may be a bit misleading in seeing it now, we de-duplicate URLs by looking at the domain/IP portion of the URL (i.e. the netloc in the parsed URL object), if the domain is already there we assume it's a duplicate URL and don't add it again. In looking back at this logic, I suppose it could be possible that we have a duplicate domain but different path, but I'd have to change quite a bit of code to test for that condition... In the meantime, I've updated the log message to hopefully be a bit more clear.

Thanks for the feedback!

**Comment by Gi7w0rm** [comment]
Hey @jstrosch ,
I was already expecting something like that ^^But its probably good you changed the message to be more clear :)
Still, no change on the initial problem sadly :/ 

Hope we can figure this out as this tool looks very promissing :)

**Comment by jstrosch** [comment]
Ah - one more item that is likely causing the issue, try changing the config value *scan_simple_domains* to True - we ran into a lot of hosts that were "simple", in that there was no sub-directories, and often they weren't worth crawling. So this config tells the engine to ignore any URLs that don't have sub-path components. It should have still scanned the 34.105.204.X host with the sub-directory, but appears there is a bug I need to work out. This change in the config should get you scanning though.

**Comment by Gi7w0rm** [comment]
@jstrosch 
This indeed solved the problem! Scanning up and running now. 
Now I just need to understand why the Service Mode is not doing anything either. 
But thats probably going to be a different ticket ^^
Thanks for your help !

**Comment by jstrosch** [comment]
Great to hear! Yes, if there are other issues please open a new ticket. Thanks for taking time to provide this feedback :)
